services:
  console-service:
    image: registry.cn-shenzhen.aliyuncs.com/tokengo/console
    ports:
      - 10426:8080
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/data
    build:
      context: .
      dockerfile: src/Console.Service/Dockerfile
